apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: web-app-monitor
  namespace: monitoring
  labels:
    release: monitoring-stack
    app.kubernetes.io/part-of: healthtrack
spec:
  selector:
    matchLabels:
      app: web-app
  namespaceSelector:
    matchNames:
      - sample-app
  endpoints:
  - port: http
    interval: 15s
