apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sample-app

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml
  - rbac.yaml
  - networkpolicy.yaml
  - ingress.yaml
  - postgres/secret.yaml
  - postgres/pvc.yaml
  - postgres/statefulset.yaml
  - postgres/service.yaml

commonLabels:
  app.kubernetes.io/part-of: healthtrack
  app.kubernetes.io/managed-by: kustomize
